### ISSUE TITLE
Missing tar.gz in codeload.github.com

### ISSUE THREAD

**Issue by alantamer** [PackeTsar/radiuid#39]
Hi,

I've tried to create a DockerFile to RadiUID 2.5.0 following the instructions on https://github.com/PackeTsar/radiuid#dockerfiles, but the script stops when it tries to download the 2.5.0 tar.gz file, getting an "ERROR 404: Not Found" response.

The last file I could download on "https://codeload.github.com/PackeTsar/radiuid/tar.gz/" was 2.4.2.

**Comment by PackeTsar** [comment]
Give it a try now. I didn't create a release for 2.5.0. It is created now
