### ISSUE TITLE
Sending to different targets based on the client the request came from

### ISSUE THREAD

**Issue by mspell-foreflight** [PackeTsar/radiuid#44]
Hey!

Amazing tool! I've been looking for something for years on and off to do this and your tool is hands down the best I've used. 

Was just curious if there was a mechanism in place to push mappings to a specific firewall target based on the client that the accounting request came from? I'm not seeing anything in the documentation for it but maybe I'm missing something obvious here.

Thanks again for the amazing tool!

**Comment by PackeTsar** [comment]
I don't think so. It's been a long time since I've worked on any code for this project, but I don't think there is any way to direct updates to particular firewalls based on information in the update

**Comment by mspell-foreflight** [comment]
Thank you sir! No worries. I think there's a way to do this with Panorama but alas we don't have Pano yet. Not a problem to just update all firewalls for now. 

Take care!
